server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: youwin
  datasource:
    url: jdbc:mysql://localhost:3306/youwin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: youwin
    password: youwin
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587 # 안되면 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    # Google 보안에서 '앱 비밀번호(16자리)'를 발급받아 입력해야 합니다.
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          starttls:
            enable: true
mybatis:
  mapper-locations: classpath:repository/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


coustom.cron: 0 0 3 * * *